options:
  auto-update: false
  auto-update-onlogin-notice: false
  no-death-message: false
  instant-soup: true
  instant-respawn: false
  killstreaks: false
  no-item-drop-on-death: false
  no-login-message: false
  no-logoff-message: false
  remove-killstreak-on-logoff: true
  sound-effects: true
  soup-in-kits: true